apiVersion: v1
kind: Namespace
metadata:
  name: edge-cdn
  labels:
    name: edge-cdn
    tier: cdn
    app: manabakh
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vod-cache-config
  namespace: edge-cdn
data:
  PORT: "3000"
  NODE_ENV: "development"
  HOST: "localhost"
  LOG_LEVEL: "debug"

  S3_ENDPOINT: "minio.minio-system"
  S3_ACCESS_KEY_ID: "rfdJLfDAM3ROyNrBFmsL"
  S3_SECRET_ACCESS_KEY: "0EE1FqCiWj5EeVGepSCGcHgqKNbDOPI55Qh2r8yj"
  S3_REGION: ""
  S3_BUCKET_NAME: "nami"
  S3_FORCE_PATH_STYLE: "true"
  S3_USE_SSL: "false"

  ALLOWED_ORIGINS: "*"
  MAX_REQUEST_SIZE: "10485760"
  REQUEST_TIMEOUT: "30000"
  ENABLE_DOMAIN_WHITELIST: "false"
  ALLOWED_DOMAINS: ""
  ENABLE_RATE_LIMITING: "false"
  RATE_LIMIT_WINDOW: "60000"
  RATE_LIMIT_MAX_REQUESTS: "60"

  ENABLE_CACHE: "true"
  CACHE_MODE: "redis"
  CACHE_TTL: "300"
  CACHE_CHECK_PERIOD: "600"
  CACHE_MAX_ITEMS: "1000"
  CACHE_MAX_SIZE: "104857600"

  USE_WORKER_THREADS: "true"
  WORKER_THREADS: "0"

  ENABLE_STREAMING: "true"
  STREAM_SIZE_THRESHOLD: "1048576"

  USE_CLOUDFLARE: "false"

  REDIS_URL: "redis://redis-cluster-service.redis-cluster:6379"
  REDIS_HOST: "redis-cluster-service.redis-cluster"
  REDIS_PORT: "6379"
  CASSANDRA_HOSTS: "cassandra-client.edge-cdn:9042"
  REDIS_MEMORY_THRESHOLD: "0.8"
  CASSANDRA_MAX_FILES: "100000"
  CASSANDRA_LOCAL_DATA_CENTER: "DC1-VoD"
  CASSANDRA_KEYSPACE: "cdn_cache"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-cache
  namespace: edge-cdn
  labels:
    app: vod-cache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vod-cache
  template:
    metadata:
      labels:
        app: vod-cache
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: worker
                    operator: In
                    values:
                      - "true"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - vod-cache
                topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: edge-vod-cache
          image: namipsg/manabakh:mcdn-r6
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: vod-cache-config
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "16Gi"
              cpu: "3000m"
          
          
---
apiVersion: v1
kind: Service
metadata:
  name: vod-cache-service
  namespace: edge-cdn
  labels:
    app: vod-cache
spec:
  selector:
    app: vod-cache
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edge-vod-ingress
  namespace: edge-cdn
  labels:
    app: edge-cdn
    tier: cdn
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-cors-headers@kubernetescrd,traefik-compression@kubernetescrd,traefik-rate-limit@kubernetescrd,traefik-default-headers@kubernetescrd

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mcdn.manabakh.ir
      secretName: ssl-secret
  rules:
    - host: mcdn.manabakh.ir
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vod-cache-service
                port:
                  number: 80
